apiVersion: v1
kind: Service
metadata:
  name: be-router
spec:
  type: NodePort
  #  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      name: be-router-port
    - port: 40000
      protocol: TCP
      name: delve-port
  selector:
    app: be-router
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: be-router
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: be-router
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
