apiVersion: apps/v1
kind: Deployment # required by statefulset
metadata:
  name: mysql
  labels:
    app: mysql
    env: local
    tier: database
spec:
  #serviceName: mysql # required by statefulset
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: db
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: berouterconf
          ports:
            - containerPort: 27017
              #name: mysql-service # required by statefulset
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "1"
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: berouterconf
                  key: MYSQL_ROOT_PASSWORD
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql